############################################
# Makefile
############################################

# Includes
############################################

-include .env
include ./makefile-utils/make.d/colors.make
include ./makefile-utils/make.d/strings.make
include ./makefile-utils/make.d/helper.make
include ./makefile-utils/make.d/makefile_tester.make

# Makefile configuration
############################################
.DEFAULT_GOAL := help
SHELL := /bin/bash
